; --- DYNAMICALLY GENERATED BY COMPILER ---
; WRAM works by making, each byte address store one game value.
.equ StateBase,0x02000000	; Base address for our WRAM 
.equ GridCellsCount,9		; 9 bytes for 3x3 logical board cells
.equ CursorX_Off,9			; Offset +9: cursor X tile index (0..2)
.equ CursorY_Off,10			; Offset +10: cursor Y tile index (0..2)
.equ CurrentSymbol_Off,11	; Offset +11: whose turn (ASCII byte, eg. 'x','o')

.equ CellEmpty,0			; Stored value for empty tile
.equ CellX,88				; Stored value for X tile as ASCII 'X'
.equ CellO,79				; Stored value for O tile as ASCII 'O'

.equ FontScale,5			; Multiply 8x8 font by 5 to get a 40x40 pixel character
.equ FontOffsetX,20			; (80 cell width - 40 char width) / 2 = 20 (Center X)
.equ FontOffsetY,6			; (53 cell height - 40 char height) / 2 = 6 (Center Y)